# Generated by Django 4.1.1 on 2022-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_projects_val1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=250)),
                ('func_value', models.CharField(max_length=250)),
            ],
        ),
    ]
