# Generated by Django 4.1.1 on 2022-10-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_alter_functions_func_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='data',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='value',
        ),
    ]
