# Generated by Django 4.1.1 on 2022-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('data', models.TextField()),
                ('value', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('notcompleted', models.BooleanField()),
            ],
        ),
    ]
