# Generated by Django 4.1.1 on 2022-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_projects_notcompleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
