# Generated by Django 4.1.1 on 2022-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_projects_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='val1',
            field=models.BooleanField(default=True),
        ),
    ]
